export const Spacing = {
  None: '0rem',
  Quarck: '0.25rem',
  Nano: '0.5rem',
  Micro: '0.75rem',
  UltraSmall: '1rem',
  HyperSmall: '1.5rem',
  SuperSmall: '2rem',
  Small: '2.5rem',
  Medium: '3rem',
  Large: '3.5rem',
  SuperLarge: '4rem',
  HyperLarge: '5rem',
  UltraLarge: '7.5rem',
  Huge: '10rem',
  Giant: '12.5rem',
  InsetQuarck: '0.25rem',
  InsetNano: '0.5rem',
  InsetMicro: '0.75rem',
  InsetSuperSmall: '1rem',
  InsetSmall: '1.5rem',
  InsetMedium: '2rem',
  InsetLarge: '2.5rem',
  SquishSuperSmall: '0.25rem 0.5rem',
  SquishSmall: '0.5rem 0.75rem',
  SquishMedium: '1rem 1.5rem',
  SquishSuperMedium: '0.5rem 1rem',
  SquishHyperMedium: '1rem 0.75rem',
  SquishMicroMedium: '0.75rem 1rem',
  SquishMicro: '0.75rem 1.5rem',
  SquishLarge: '1rem 2rem',
  SquishExtraLarge: '1.5rem 2rem',
  SquishHyperLarge: '2rem 2.5rem',
  SquishHuge: '1.5rem 4rem',
  SquishGiant: '2rem 4rem'
};
